// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_accounts.
// - Entity ID: 102019c33619abf771f8d3205a7a0245b28.
// - Entity Version: 102019c6611b04478da843b57585b06a85d.
// - Task ID: 6992f61624412caf227fb442.
// - Task Root ID: 692ba10086c50c404f9cea0d.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserAccountsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserAccountsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  email: string;
  name: string;
  is_premium: boolean;
  password: string;
}

/**
 * ORM class for UserAccounts entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserAccountsORM {
  private static instance: UserAccountsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c33619abf771f8d3205a7a0245b28';
    this.entityName = 'user_accounts';
    this.entityVersion = '102019c6611b04478da843b57585b06a85d';
    this.taskId = '6992f61624412caf227fb442';
    this.taskRootId = '692ba10086c50c404f9cea0d';
  }

  /**
   * Get singleton instance of UserAccountsORM
   */
  public static getInstance(): UserAccountsORM {
    if (!UserAccountsORM.instance) {
      UserAccountsORM.instance = new UserAccountsORM();
    }
    
    return UserAccountsORM.instance;
  }

  /**
   * Get user_accounts by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserAccountsByIDs(ids: string[]): Promise<UserAccountsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_accounts by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserAccountsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all UserAccounts records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserAccounts(): Promise<UserAccountsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserAccounts record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserAccounts(data: UserAccountsModel[]): Promise<UserAccountsModel[]> {
    const structured = data.map((item) => CreateData(UserAccountsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserAccounts records
   */
  async purgeAllUserAccounts(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserAccounts records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserAccounts(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserAccountsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_accounts by Id index
   * This function gets data by index.
   */
  async getUserAccountsById(
    id: string,
  ): Promise<UserAccountsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_accounts by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserAccountsById(
    id: string,
    data: UserAccountsModel
  ): Promise<UserAccountsModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserAccountsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_accounts by Id index
   */
  async deleteUserAccountsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_accounts by DataCreator index
   * This function gets data by index.
   */
  async getUserAccountsByDataCreator(
    data_creator: string,
  ): Promise<UserAccountsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_accounts by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserAccountsByDataCreator(
    data_creator: string,
    data: UserAccountsModel
  ): Promise<UserAccountsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserAccountsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_accounts by DataCreator index
   */
  async deleteUserAccountsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_accounts by DataUpdater index
   * This function gets data by index.
   */
  async getUserAccountsByDataUpdater(
    data_updater: string,
  ): Promise<UserAccountsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_accounts by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserAccountsByDataUpdater(
    data_updater: string,
    data: UserAccountsModel
  ): Promise<UserAccountsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserAccountsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_accounts by DataUpdater index
   */
  async deleteUserAccountsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_accounts by Email index
   * This function gets data by index.
   */
  async getUserAccountsByEmail(
    email: string,
  ): Promise<UserAccountsModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_accounts by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserAccountsByEmail(
    email: string,
    data: UserAccountsModel
  ): Promise<UserAccountsModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = UserAccountsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_accounts by Email index
   */
  async deleteUserAccountsByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserAccountsModel data array
   */
  private resultToData(values: Data[]): UserAccountsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserAccountsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserAccountsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserAccountsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserAccountsModel => item !== null);
  }
}

/**
 * Convert UserAccountsModel data to Value array
 */
function UserAccountsModelToValues(data: UserAccountsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'is_premium', type: DataType.boolean, defaultValue: false },
    { key: 'password', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserAccountsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserAccountsModel data
 */
function UserAccountsModelFromValues(values: Value[]): UserAccountsModel {
  const data: Partial<UserAccountsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'is_premium':
        data.is_premium = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'password':
        data.password = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as UserAccountsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}

export default UserAccountsORM;